### ISSUE TITLE
Bad API request, invalid api_dev_key for pastebin

### ISSUE THREAD

**Issue by ZerooCool** [lubuntu-team/pastebinit#2]
/usr/bin/pastebinit (master) $ python3 pastebinit README
Bad API request, invalid api_dev_key

**Comment by wxl** [comment]
I could not reproduce this, so you have some other problem, perhaps due to an invalid custom configuration, specifically as it relates to `api_dev_key` which, as it relates to all of the available pastebins, is specific to pastebin.com. Now pastebin.com is the fallback default but the default is supposed to be distro-specific.

**Comment by ghost** [comment]
I also experience the same issue. Version is 1.5.1, packaged by Arch Linux dev, used on Manjaro. If I run with --verbose it says the api key is 253ce2f0a45140ee0a44ca99aa49260. Any ideas?

**Comment by ZerooCool** [comment]
I suppose you have to know how to create your own API?
It's not very easy, if we install a package, we would like it to work without having to change the API key.

In the meantime, I have set up my own privatebin server.

I would still like to understand how to deal with this API key issue, to complete the wiki page:

https://wiki.visionduweb.fr/index.php?title=Exporter_un_fichier_texte_vers_un_service_en_ligne_de_type_pastebin

**Comment by ghost** [comment]
I have registered on pastebin and tried my dev api key in `/usr/share/pastebin.d/pastebin.com.conf`. Same response.

**Comment by Dids** [comment]
Same issue here. Switching to my own API key made no difference.

**Comment by HaleTom** [comment]
Ditto for me.  I'm also on Manjaro Linux.
